name: main
on:
  pull_request:
    branches: [ main ]
jobs:
  pre_commit_run:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.0
  unit_tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install llvm-18 libstdc++-14-dev
      - run: make test
      - run: ./test_exe
